[deps]
ModalAssociationRules = "fb95e5f7-b6b0-4744-a282-88ebeeae65a3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SoleBase = "4475fa32-7023-44a0-aa70-4813b230e492"
SoleData = "123f1ae1-6307-4526-ab5b-aab3a92a2b8c"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"

[compat]
SoleBase = "=0.13.3"
SoleData = "=0.16.4"
SoleLogics = "=0.13.2"
