[deps]
ARFFFiles = "da404889-ca92-49ff-9e8b-0aa6b4d38dc8"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FuzzyLogic = "271df9f8-4390-4196-9d4f-bdd0b67035b3"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Impute = "f7bf1975-0170-51b9-8c5f-a992d46b9575"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
ManyExpertDecisionTrees = "b59e7f69-5672-4a63-bb58-b897b1454099"
MatrixProfile = "24e37439-14ec-4097-bda3-6a65822e2305"
ModalAssociationRules = "fb95e5f7-b6b0-4744-a282-88ebeeae65a3"
ModalDecisionTrees = "e54bda2e-c571-11ec-9d64-0242ac120002"
MultiData = "8cc5100c-b3d1-4f82-90cb-0ea93d317aba"
PalmerPenguins = "8b842266-38fa-440a-9b57-31493939ab85"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SoleBase = "4475fa32-7023-44a0-aa70-4813b230e492"
SoleData = "123f1ae1-6307-4526-ab5b-aab3a92a2b8c"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
SoleModels = "4249d9c7-3290-4ddd-961c-e1d3ec2467f8"
SoleReasoners = "eb5c4719-5716-4250-abf0-f5b4713e79ae"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
ManyExpertDecisionTrees = {url = "https://github.com/aclai-lab/ManyExpertDecisionTrees.jl"}

[compat]
julia = "1.11"
